import { env } from '@/env.mjs';

export const siteConfig = {
  title: 'Mouil Prosper | Full-Stack Developer & Software Engineer',
  description:
    'Mouil Prosper is a results-driven Full-Stack Engineer with 4+ years of experience designing, developing, and deploying secure, cloud-native SaaS applications. Specialized in Java (Spring Boot), TypeScript (Angular, React), Node.js, Docker, GCP & AWS, RESTful microservices, and CI/CD pipelines.',
  keywords: [
    'Mouil Prosper',
    'Mouil',
    'Prosper',
    'Full-Stack Developer',
    'Software Engineer',
    'React Developer',
    'Next.js Developer',
    'Angular Developer',
    'Java Developer',
    'Spring Boot Developer',
    'Node.js Developer',
    'Web Development',
    'Front-end Engineer',
    'UI/UX Developer',
    'Responsive Design',
    'JavaScript Developer',
    'TypeScript Developer',
    'Portfolio',
    'Projects',
    'Web Applications',
    'Websites',
    'Freelance Developer',
    'Remote Developer',
    'AWS',
    'GCP',
    'Docker',
    'PostgreSQL',
    'Cloud Native',
    'SaaS',
    'REST API',
    'Microservices',
    'CI/CD',
    'DevOps',
  ],
  author: 'Mouil Prosper',
  locale: 'en_US',
  ogImage: '/images/og-image.png',
  url: env.SITE_URL || 'https://pepis.world',
  googleSiteVerificationId: env.GOOGLE_SITE_VERIFICATION_ID || '',
};
