import { env } from '@/env.mjs';

export const siteConfig = {
  title: 'Mouil Prosper | Front-end Developer & Software Engineer',
  description:
    "Hello, I'm Mouil Prosper, a passionate front-end developer specializing in React and Next.js. I build modern, responsive websites and web applications with a focus on performance, accessibility, and user experience. View my portfolio, projects, and skills.",
  keywords: [
    'Mouil Prosper',
    'Mouil',
    'Prosper',
    'Front-end Developer',
    'Software Engineer',
    'React Developer',
    'Next.js Developer',
    'Web Development',
    'Front-end Engineer',
    'UI/UX Developer',
    'Responsive Design',
    'JavaScript Developer',
    'TypeScript Developer',
    'Portfolio',
    'Projects',
    'Web Applications',
    'Websites',
    'Freelance Developer',
    'Remote Developer',
    'Full-Stack Developer',
    'Frontend Portfolio',
    'React Portfolio',
    'Next.js Portfolio',
    'Java',
    'Spring Boot',
    'Angular',
    'Node.js',
    'Python',
    'Docker',
    'Vercel',
    'PostgreSQL',
    'AWS',
    'GCP',
    'Tailwind CSS',
    'Web Performance',
    'Code',
    'Programming',
    'Tech Enthusiast',
  ],
  author: 'Mouil Prosper',
  locale: 'en_US',
  ogImage: '/images/og-image.png',
  url: env.SITE_URL || 'https://pepis.world',
  googleSiteVerificationId: env.GOOGLE_SITE_VERIFICATION_ID || '',
};
